apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: wp-labs
  labels:
    app: api
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "student"
  MONGO_INITDB_ROOT_PASSWORD: "student_secure_password"
  MONGO_URI: "mongodb://student:student_secure_password@mongo:27017/wp_labs?authSource=admin"

  REDIS_PASSWORD: "redis_secure_password"

  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin_secure_password"

  RABBITMQ_USER: "student"
  RABBITMQ_PASS: "student_secure_rabbit_pass_change_in_prod"

  SMTP_PASS: ""

  JWT_ACCESS_SECRET: "4f7c8e2b1a9d0c3e5f6a7b8c9d0e1f224f7c8e2b1a9d0c3e5f6a7b8c9d0e1f22"
  JWT_REFRESH_SECRET: "9a1d3f5b7c8e0a2d4f6b8c1e3a5d7f909a1d3f5b7c8e0a2d4f6b8c1e3a5d7f90"

  YANDEX_CLIENT_ID: ""
  YANDEX_CLIENT_SECRET: ""
